name: Pipeline CI

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: it_expect
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v6

      - name: Configuration de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: pdo, pdo_mysql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # PHPUnit lira automatiquement le phpunit.xml à la racine !
      - name: Run PHPUnit
        run: vendor/bin/phpunit